Release rk3566_rk3568 - 2023-12-28
Based on:
    e237b9d configs: debian: Add Debian12 (Bookworm) to support

Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Change-Id: I4b7826da29658af2616452c96de5e67d96d9cf65

diff --git a/common/scripts/build-helper b/common/scripts/build-helper
--- a/common/scripts/build-helper
+++ b/common/scripts/build-helper
@@ -13,14 +13,14 @@ err_handler()
 	ret=${1:-$?}
 	[ "$ret" -eq 0 ] && return
 
-	echo "ERROR: Running $0 - ${2:-${FUNCNAME[1]}} failed!"
-	echo "ERROR: exit code $ret from line ${BASH_LINENO[0]}:"
-	echo "    ${3:-$BASH_COMMAND}"
-	echo "ERROR: call stack:"
+	fatal "ERROR: Running $0 - ${2:-${FUNCNAME[1]}} failed!"
+	fatal "ERROR: exit code $ret from line ${BASH_LINENO[0]}:"
+	fatal "    ${3:-$BASH_COMMAND}"
+	fatal "ERROR: call stack:"
 	for i in $(seq 1 $((${#FUNCNAME[@]} - 1))); do
 		SOURCE="${BASH_SOURCE[$i]}"
 		LINE=${BASH_LINENO[$(( $i - 1 ))]}
-		echo "    $(basename "$SOURCE"): ${FUNCNAME[$i]}($LINE)"
+		fatal "    $(basename "$SOURCE"): ${FUNCNAME[$i]}($LINE)"
 	done
 	exit $ret
 }
@@ -30,9 +30,9 @@ set -eE
 run_command()
 {
 	if [ "$DRY_RUN" ]; then
-		echo "$@"
+		notice "$@"
 	else
-		echo "+ $@"
+		notice "+ $@"
 		$@
 	fi
 }
@@ -128,7 +128,7 @@ usage()
 	exit 1
 }
 
-cd "$SDK_DIR"
+cd "$RK_SDK_DIR"
 
 LOG_FILE_NAME="$(basename "${0%.sh}")-$1_$(date +"%F_%H-%M-%S")"
 
@@ -137,21 +137,23 @@ case "$1" in
 	make-targets) make_targets; exit 0 ;;
 	make-usage) make_usage; exit 0 ;;
 	usage) usage_hook; exit 0 ;;
-	support-cmds)
+	parse-cmds)
 		shift
+		source "$RK_PARSED_CMDS" 2>/dev/null || true
+
 		{
-			ALL_CMDS="$INIT_CMDS $PRE_BUILD_CMDS $BUILD_CMDS \
-				$POST_BUILD_CMDS"
-			for stage in ${@:-all}; do
-				case $stage in
-					init) echo "$INIT_CMDS" ;;
-					pre-build) echo "$PRE_BUILD_CMDS" ;;
-					build) echo "$BUILD_CMDS" ;;
-					post-build) echo "$POST_BUILD_CMDS" ;;
-					all) echo "$ALL_CMDS" ;;
-				esac
-			done
-		} | xargs -n 1 | grep -v "^default$" | xargs || true
+			SCRIPT="$(realpath "$0")"
+			echo "# Parsed from $SCRIPT."
+
+			[ -z "$INIT_CMDS" ] || \
+				echo "RK_INIT_CMDS=\"\$RK_INIT_CMDS $(echo $INIT_CMDS | sort)\" # $SCRIPT"
+			[ -z "$PRE_BUILD_CMDS" ] || \
+				echo "RK_PRE_BUILD_CMDS=\"\$RK_PRE_BUILD_CMDS $(echo $PRE_BUILD_CMDS | sort)\" # $SCRIPT"
+			[ -z "$BUILD_CMDS" ] || \
+				echo "RK_BUILD_CMDS=\"\$RK_BUILD_CMDS $(echo $BUILD_CMDS | sort)\" # $SCRIPT"
+			[ -z "$POST_BUILD_CMDS" ] || \
+				echo "RK_POST_BUILD_CMDS=\"\$RK_POST_BUILD_CMDS $(echo $POST_BUILD_CMDS | sort)\" # $SCRIPT"
+		} >> "$RK_PARSED_CMDS"
 		exit 0
 		;;
 	clean)
@@ -181,7 +183,7 @@ case "$1" in
 esac
 
 if [ "$DRY_RUN" ]; then
-	echo "Environment 'DRY_RUN' ignored!"
+	warning "Environment 'DRY_RUN' ignored!"
 	unset DRY_RUN
 fi
 
