Release rk3308 - 2023-12-29
Based on:
    e237b9d configs: debian: Add Debian12 (Bookworm) to support

Signed-off-by: Caesar Wang <wxt@rock-chips.com>
Change-Id: I0e83f0afd0788c11e7c2734d1abc3cf2a3847953

diff --git a/common/scripts/partition-helper b/common/scripts/partition-helper
--- a/common/scripts/partition-helper
+++ b/common/scripts/partition-helper
@@ -65,10 +65,10 @@ rk_partition_size_readable_to_sector()
 # Parse parameter to "<name> <size>" pairs
 rk_partition_parse()
 {
-	PARAMETER="${1:-$CHIP_DIR/$RK_PARAMETER}"
+	PARAMETER="${1:-$RK_CHIP_DIR/$RK_PARAMETER}"
 
 	if [ ! -r "$PARAMETER" ]; then
-		echo -e "\e[36m$PARAMETER not exists!\e[0m" >&2
+		error "$PARAMETER not exists!" >&2
 		exit 1
 	fi
 
@@ -92,10 +92,67 @@ rk_partition_init()
 	rk_partition_parse > "$PART_TABLE"
 }
 
+rk_partition_id()
+{
+	grep -v "^$HDR_PART " "$PART_TABLE" | \
+		grep -n -E -m 1 "^$1(|_[a-z]) " | cut -d':' -f1 || true
+}
+
+rk_partition_name()
+{
+	[ "$#" -eq 1 ] || return 1
+
+	# Part name
+	if ! echo $1 | grep -qE "^[0-9]*$"; then
+		if ! grep -q "^$1 " "$PART_TABLE"; then
+			error "No such part ($1)!" >&2
+			return 1
+		fi
+
+		echo $1
+		return 0
+	fi
+
+	# Part idx
+	IDX=$1
+	if [ "$IDX" -lt 1 ]; then
+		error "Index should not be less than 1!" >&2
+		return 1
+	fi
+
+	NUM=$(rk_partition_num)
+	if [ "$IDX" -gt "$NUM" ]; then
+		error "Index should not be greater than $NUM!" >&2
+		return 1
+	fi
+
+	sed -n "$(($IDX + 1))s/\(^[^ ]*\) .*/\1/p" "$PART_TABLE"
+}
+
+rk_partition_start()
+{
+	OFFSET=0
+	while read NAME SIZE; do
+		if echo "$NAME" | grep -qE "^$1(|_[a-z])$"; then
+			echo $OFFSET | awk '{printf "0x%08x\n",$1}'
+			return 0
+		fi
+
+		# NOTE: Assuming partitions are contiguous
+		OFFSET=$(( $OFFSET + ${SIZE/-/0} ))
+	done < "$PART_TABLE"
+}
+
 rk_partition_size()
 {
-	grep -E "^$1(|_[a-z]) " "$PART_TABLE" | cut -d' ' -f2 | tr -d '\-' | \
-		sort | head -n 1 || true
+	grep -E -m 1 "^$1(|_[a-z]) " "$PART_TABLE" | cut -d' ' -f2 | \
+		tr -d '\-' || true
+}
+
+# Get partition size limit, 0 means unlimited or not exists.
+rk_partition_size_kb() {
+	PART_SIZE="$(rk_partition_size "$1")"
+	echo $(( ${PART_SIZE:-0} / 2))
 }
 
 rk_partition_num()
@@ -106,10 +163,9 @@ rk_partition_num()
 # Print partition table info
 rk_partition_print()
 {
-	echo
-	echo "=========================================="
-	echo "          Partition table"
-	echo "=========================================="
+	message "\n=========================================="
+	message "          Partition table"
+	message "=========================================="
 	{
 		OFFSET=0
 		while read NAME SIZE; do
@@ -118,7 +174,7 @@ rk_partition_print()
 
 			if [ "$NAME" != "$HDR_PART" ]; then
 				NAME=$(echo $NAME | awk '{printf "%12s",$1}')
-				echo -e "$NAME at $OFFSET size=$SIZE($SIZE_STR)"
+				message "$NAME at $OFFSET size=$SIZE($SIZE_STR)"
 			fi
 
 			# NOTE: Assuming partitions are contiguous
@@ -127,7 +183,7 @@ rk_partition_print()
 	} | sed "=" | sed "N;s/\n/: /"
 
 	echo
-	echo "Legacy cmdline:"
+	message "Legacy cmdline:"
 	rk_partition_to_cmdline
 	echo
 }
@@ -160,7 +216,7 @@ rk_partition_to_cmdline()
 # Save partition table to parameter
 rk_partition_save()
 {
-	PARAMETER="${1:-$CHIP_DIR/$RK_PARAMETER}"
+	PARAMETER="${1:-$RK_CHIP_DIR/$RK_PARAMETER}"
 	[ -r "$PARAMETER" ] || return 1
 
 	PARTS=$(rk_partition_to_cmdline)
@@ -181,44 +237,13 @@ rk_partition_edit()
 	rk_partition_save
 }
 
-rk_partition_parse_name()
-{
-	unset PART_NAME
-
-	[ "$#" -eq 1 ] || return 1
-
-	# Part name
-	if ! echo $1 | grep -qE "^[0-9]*$"; then
-		if ! grep -q "^$1 " "$PART_TABLE"; then
-			echo -e "\e[35mNo such part ($1)!\e[0m"
-			return 1
-		fi
-
-		PART_NAME=$1
-		return 0
-	fi
-
-	# Part idx
-	IDX=$1
-	if [ "$IDX" -lt 1 ]; then
-		echo -e "\e[35mIndex should not be less than 1!\e[0m"
-		return 1
-	fi
-
-	NUM=$(rk_partition_num)
-	if [ "$IDX" -gt "$NUM" ]; then
-		echo -e "\e[35mIndex should not be greater than $NUM!\e[0m"
-		return 1
-	fi
-
-	PART_NAME=$(sed -n "$(($IDX + 1))s/\(^[^ ]*\) .*/\1/p" "$PART_TABLE")
-}
-
 rk_partition_del()
 {
 	[ "$#" -gt 0 ] || return 1
 
-	rk_partition_parse_name $1 || return 1
+	PART_NAME="$(rk_partition_name $1)"
+	[ "$PART_NAME" ] || return 1
+
 	sed -i "/^$PART_NAME /d" "$PART_TABLE"
 
 	rk_partition_save
@@ -229,12 +254,14 @@ rk_partition_rename()
 	[ "$#" -gt 1 ] || return 1
 
 	echo $2 | grep -qE "^[a-zA-Z]" || return 1
-	if rk_partition_parse_name $2 >/dev/null; then
-		echo -e "\e[35mPart already exists ($2)!\e[0m"
+	if rk_partition_name $2 &>/dev/null; then
+		error "Part already exists ($2)!"
 		return 1
 	fi
 
-	rk_partition_parse_name $1 || return 1
+	PART_NAME="$(rk_partition_name $1)"
+	[ "$PART_NAME" ] || return 1
+
 	sed -i "s/^$PART_NAME /$2 /" "$PART_TABLE"
 
 	rk_partition_save
@@ -245,19 +272,22 @@ rk_partition_move()
 	[ "$#" -gt 1 ] || return 1
 
 	echo $2 | grep -qE "^[0-9]*$" || return 1
-	rk_partition_parse_name $2 || return 1
+	PART_NAME="$(rk_partition_name $2)"
+	[ "$PART_NAME" ] || return 1
 
-	rk_partition_parse_name $1 || return 1
+	PART_NAME="$(rk_partition_name $1)"
+	[ "$PART_NAME" ] || return 1
+
 	PART=$(sed -n "/^$PART_NAME /p" "$PART_TABLE")
 
 	NUM=$(rk_partition_num)
 	if [ "$2" -eq "$NUM" ] && grep -q "\-$" "$PART_TABLE"; then
-		echo -e "\e[35mCannot move after unlimited part!\e[0m"
+		error "Cannot move after unlimited part!"
 		return 1
 	fi
 
 	if echo "$PART" | grep -q "\-$"; then
-		echo -e "\e[35mCannot move unlimited part ($1)!\e[0m"
+		error "Cannot move unlimited part ($1)!"
 		return 1
 	fi
 
@@ -276,7 +306,9 @@ rk_partition_resize()
 		*) SIZE="$(rk_partition_size_readable_to_sector $2)" ;;
 	esac
 
-	rk_partition_parse_name $1 || return 1
+	PART_NAME="$(rk_partition_name $1)"
+	[ "$PART_NAME" ] || return 1
+
 	sed -i "s/^$PART_NAME .*/$PART_NAME $SIZE/" "$PART_TABLE"
 
 	rk_partition_save
@@ -290,19 +322,19 @@ rk_partition_insert()
 
 	IDX=$1
 	if [ "$IDX" -lt 1 ]; then
-		echo -e "\e[35mIndex should not be less than 1!\e[0m"
+		error "Index should not be less than 1!"
 		return 1
 	fi
 
 	NUM=$(rk_partition_num)
 	if [ "$IDX" -gt "$(($NUM + 1))" ]; then
-		echo -e "\e[35mIndex should not be greater than $(($NUM + 1))!\e[0m"
+		error "Index should not be greater than $(($NUM + 1))!"
 		return 1
 	fi
 
 	echo $2 | grep -qE "^[a-zA-Z]" || return 1
-	if rk_partition_parse_name $2 >/dev/null; then
-		echo -e "\e[35mPart already exists ($2)!\e[0m"
+	if rk_partition_name $2 &>/dev/null; then
+		error "Part already exists ($2)!"
 		return 1
 	fi
 
@@ -312,12 +344,12 @@ rk_partition_insert()
 	esac
 
 	if [ "$SIZE" = "-" ] && [ "$IDX" -lt "$(( $NUM + 1 ))" ]; then
-		echo -e "\e[35mOnly latest part can be unlimited!\e[0m"
+		error "Only latest part can be unlimited!"
 		return 1
 	fi
 
 	if [ "$IDX" -eq "$(( $NUM + 1 ))" ] && grep -q "\-$" "$PART_TABLE"; then
-		echo -e "\e[35mCannot insert after unlimited part!\e[0m"
+		error "Cannot insert after unlimited part!"
 		return 1
 	fi
 
@@ -343,7 +375,7 @@ rk_partition_create()
 			[ -z "$1" ] || shift
 
 			if [ "$1" -a "$SIZE" = "-" ]; then
-				echo -e "\e[35mOnly latest part can be unlimited!\e[0m"
+				error "Only latest part can be unlimited!"
 				break
 			fi
 
@@ -434,15 +466,15 @@ rk_extra_part_nopack()
 	rk_extra_part_arg ${1:-1} 8 | grep -wq nopack
 }
 
+rk_extra_part_outdir()
+{
+	echo "$RK_EXTRA_PART_OUTDIR/$(rk_extra_part_name $1)"
+}
+
 # Symlink to the mountpoint in rootfs dir
 rk_extra_part_mount_dir()
 {
-	echo "$RK_OUTDIR/$(rk_extra_part_name $1)-mount"
-}
-
-rk_extra_part_outdir()
-{
-	echo "$RK_OUTDIR/$(rk_extra_part_name $1)"
+	echo "$(rk_extra_part_outdir $1)-mount"
 }
 
 rk_extra_part_fakeroot_script()
@@ -465,12 +497,12 @@ rk_extra_part_prepare()
 	FAKEROOT_SCRIPT="$(rk_extra_part_fakeroot_script $1)"
 	SRCS="$(rk_extra_part_src $1)"
 
-	echo "Preparing partiton $PART_NAME"
+	notice "Preparing partiton $PART_NAME"
 
 	rm -rf "$OUTDIR" "$DST" "$MOUNT_DIR" "$FAKEROOT_SCRIPT"
 
 	if rk_extra_part_nopack $1; then
-		echo "Skip preparing $PART_NAME (not packing it)"
+		notice "Skip preparing $PART_NAME (not packing it)"
 		return 0
 	fi
 
@@ -483,10 +515,10 @@ rk_extra_part_prepare()
 		[ -d "$src" ] || continue
 		[ "$(ls "$src/")" ] || continue
 
-		echo "Merging $src into $OUTDIR"
+		message "Merging $src into $OUTDIR"
 		rsync -a "$src/" "$OUTDIR"
 		for f in $(ls "$OUTDIR" | grep "\.fs$" || true); do
-			echo "Merging $src/$f into $FAKEROOT_SCRIPT"
+			message "Merging $src/$f into $FAKEROOT_SCRIPT"
 			cat "$OUTDIR/$f" >> "$FAKEROOT_SCRIPT"
 			rm -f "$OUTDIR/$f"
 		done
